dataset: meta-celeb-df, meta-face-forensics
train:
  split: meta-train
  image_size: 155
  normalization: True
  transform: null
  n_batch: 100
  n_episode: 4
  n_way: 2
  n_shot: 5
  n_query: 10
val:
  split: meta-val
  image_size: 155
  normalization: True
  transform: null
  n_batch: 100
  n_episode: 4
  n_way: 2
  n_shot: 5
  n_query: 10

encoder: inception_v3
encoder_args:
  # bn_args:
  #   track_running_stats: True
classifier: logistic

inner_args:
  reset_classifier: True
  n_step: 5
  encoder_lr: 0.01
  classifier_lr: 0.01
  momentum: 0.9
  weight_decay: 5.e-4
  first_order: False

optimizer: sgd
optimizer_args:
  lr: 0.01
  weight_decay: 5.e-4
  schedule: step
  milestones:
    - 120
    - 140

epoch: 150