dataset: meta-vfhq
test:
  split: meta-test
  image_size: 84
  normalization: False
  transform: null
  n_batch: 50
  n_episode: 4
  n_way: 2
  n_shot: 5
  n_query: 10

load: ./save/resnet18_celeb-df, face-forensics, vfhq, dff_2_way_5_shot/max-va.pth

inner_args:
  n_step: 10
  encoder_lr: 0.01
  classifier_lr: 0.01
  first_order: False  # set to True for FOMAML
  frozen:
    - bn

epoch: 5