EXP_NAME: vfhq_inception_ff

DATA:
  train_data_name: vfhq
  train_data_path: /root/datasets/vfhq
  test_data_name: ff
  test_data_path: /root/datasets/ff
  is_image: True
  image_size: 299
  batch_size: 32
  crop_ratio: 1
  num_workers: 4
  frame_num: 100

MODEL:
  name: inception_v3
  pretrained: True
  num_classes: 2

TRAIN:
  epochs: 400
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  log_interval: 10
  save_interval: 10000
  ckpt_dir: /root/result/vfhq_inception/epoch_400
  load_ckpt_dir: /root/result/vfhq_inception/epoch_400/step14400_ep400.pt


